import "./globals.css";
import { ThemeProvider } from "./components/ThemeProvider";
<link
  rel="stylesheet"
  href="https://use.fontawesome.com/releases/v5.8.1/css/solid.css"
/>;

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="dark">
      <body className="font-Montserrat  dark:bg-darkBlack ">
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem={true}
          storageKey="theme"
        >
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
